#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Computer-assisted verification for the base cases n=3,4.

The verified statement is:

For AQ_n with n=3 or n=4, for every fault set F with |F| <= 1,
for every nonfaulty edge e = uv, and for every integer l satisfying
2 <= l <= 2^n - 4, there exist in AQ_n - F

    - a u-v path P of length l,
    - a cycle C of length 2^n - l - 1,

such that V(P) and V(C) are disjoint and together cover all vertices of AQ_n.

Path length and cycle length are counted by edges.

Usage:
    python verify_base_cases.py
    python verify_base_cases.py --n 3
    python verify_base_cases.py --n 4
    python verify_base_cases.py --n 3 --dump witnesses_n3.json
"""

from __future__ import annotations

import argparse
import json
import time
from collections import deque
from functools import lru_cache
from typing import Dict, FrozenSet, Iterable, List, Optional, Tuple

Vertex = int
Edge = Tuple[int, int]


def bit_vertices(mask: int) -> Iterable[int]:
    """Yield vertices represented by 1-bits of mask."""
    while mask:
        lowbit = mask & -mask
        yield lowbit.bit_length() - 1
        mask ^= lowbit


def popcount(mask: int) -> int:
    return mask.bit_count()


def edge_key(u: int, v: int) -> Edge:
    return (u, v) if u < v else (v, u)


class AugmentedCube:
    """Augmented cube AQ_n generated by its standard Cayley graph description."""

    def __init__(self, n: int):
        self.n = n
        self.N = 1 << n
        self.all_vertices_mask = (1 << self.N) - 1
        self.labels = [format(v, f"0{n}b") for v in range(self.N)]

        # AQ_n is the Cayley graph on {0,1}^n with generators
        # e_i, 1 <= i <= n, and e_1+...+e_i, 2 <= i <= n.
        generators: List[int] = []

        for i in range(n):
            generators.append(1 << i)

        prefix = 0
        for i in range(n):
            prefix |= 1 << i
            if i >= 1:
                generators.append(prefix)

        edges = set()
        adj = [0] * self.N

        for x in range(self.N):
            for g in generators:
                y = x ^ g
                adj[x] |= 1 << y
                if x < y:
                    edges.add((x, y))

        self.edges: List[Edge] = sorted(edges)
        self.adj_full = [0] * self.N

        for u, v in self.edges:
            self.adj_full[u] |= 1 << v
            self.adj_full[v] |= 1 << u

    def adjacency_without_faults(self, faults: FrozenSet[Edge]) -> List[int]:
        """Return adjacency masks of AQ_n - faults."""
        adj = self.adj_full[:]
        for u, v in faults:
            adj[u] &= ~(1 << v)
            adj[v] &= ~(1 << u)
        return adj

    def format_vertex(self, v: Vertex) -> str:
        return self.labels[v]

    def format_edge(self, e: Edge) -> str:
        u, v = e
        return f"{self.labels[u]}-{self.labels[v]}"

    def format_path(self, path: Tuple[Vertex, ...]) -> List[str]:
        return [self.labels[v] for v in path]

    def one_fault_sets(self) -> List[FrozenSet[Edge]]:
        """All fault sets F with |F| <= 1."""
        fault_sets: List[FrozenSet[Edge]] = [frozenset()]
        fault_sets.extend(frozenset([e]) for e in self.edges)
        return fault_sets


def shortest_distance(
    adj: List[int],
    start: Vertex,
    target: Vertex,
    allowed_mask: int,
) -> Optional[int]:
    """Shortest distance from start to target inside the induced subgraph on allowed_mask."""
    if not ((allowed_mask >> start) & 1):
        return None
    if not ((allowed_mask >> target) & 1):
        return None

    queue = deque([(start, 0)])
    seen = 1 << start

    while queue:
        x, d = queue.popleft()
        if x == target:
            return d

        candidates = adj[x] & allowed_mask & ~seen
        for y in bit_vertices(candidates):
            seen |= 1 << y
            queue.append((y, d + 1))

    return None


def hamiltonian_cycle_on_subset(
    adj: List[int],
    subset_mask: int,
) -> Optional[Tuple[Vertex, ...]]:
    """
    Find a Hamiltonian cycle in the induced subgraph on subset_mask.
    Return a tuple (v0, v1, ..., vk, v0), or None if none is found.
    """
    if popcount(subset_mask) < 3:
        return None

    # A necessary condition: every vertex has degree at least 2 in the subset.
    for v in bit_vertices(subset_mask):
        if popcount(adj[v] & subset_mask) < 2:
            return None

    start = min(bit_vertices(subset_mask))

    @lru_cache(maxsize=None)
    def dfs(curr: Vertex, visited_mask: int) -> Optional[Tuple[Vertex, ...]]:
        if visited_mask == subset_mask:
            if (adj[curr] >> start) & 1:
                return (curr, start)
            return None

        candidates = list(bit_vertices(adj[curr] & subset_mask & ~visited_mask))

        # Try vertices with fewer remaining choices first.
        candidates.sort(
            key=lambda x: popcount(adj[x] & subset_mask & ~visited_mask)
        )

        for nb in candidates:
            result = dfs(nb, visited_mask | (1 << nb))
            if result is not None:
                return (curr,) + result

        return None

    return dfs(start, 1 << start)


def find_path_and_cycle(
    aq: AugmentedCube,
    adj: List[int],
    u: Vertex,
    v: Vertex,
    length_l: int,
    cycle_cache: Dict[int, Optional[Tuple[Vertex, ...]]],
) -> Optional[Tuple[Tuple[Vertex, ...], Tuple[Vertex, ...]]]:
    """
    Find a u-v path P of length length_l such that the remaining vertices
    induce a Hamiltonian cycle C.
    """
    all_mask = aq.all_vertices_mask

    @lru_cache(maxsize=None)
    def dfs(
        curr: Vertex,
        steps_left: int,
        visited_mask: int,
    ) -> Optional[Tuple[Tuple[Vertex, ...], Tuple[Vertex, ...]]]:

        if steps_left == 0:
            if curr != v:
                return None

            complement = all_mask ^ visited_mask

            if complement not in cycle_cache:
                cycle_cache[complement] = hamiltonian_cycle_on_subset(adj, complement)

            cycle = cycle_cache[complement]
            if cycle is None:
                return None

            return ((curr,), cycle)

        # The endpoint v may only be used as the last vertex.
        if curr == v:
            return None

        allowed_mask = (all_mask ^ visited_mask) | (1 << curr) | (1 << v)
        lower_bound = shortest_distance(adj, curr, v, allowed_mask)

        if lower_bound is None or lower_bound > steps_left:
            return None

        candidates = list(bit_vertices(adj[curr] & ~visited_mask))

        # Prefer candidates closer to the endpoint v.
        def candidate_key(x: Vertex) -> Tuple[int, int]:
            next_allowed = (all_mask ^ (visited_mask | (1 << x))) | (1 << x) | (1 << v)
            d = shortest_distance(adj, x, v, next_allowed)
            return (10**9 if d is None else d, x)

        candidates.sort(key=candidate_key)

        for nb in candidates:
            if nb == v and steps_left > 1:
                continue

            result = dfs(nb, steps_left - 1, visited_mask | (1 << nb))
            if result is not None:
                path_tail, cycle = result
                return ((curr,) + path_tail, cycle)

        return None

    return dfs(u, length_l, 1 << u)


def verify_n(n: int, dump_path: Optional[str] = None) -> bool:
    aq = AugmentedCube(n)
    fault_sets = aq.one_fault_sets()

    print(f"Verifying AQ_{n}")
    print(f"  vertices      : {aq.N}")
    print(f"  edges         : {len(aq.edges)}")
    print(f"  fault sets    : {len(fault_sets)}")
    print(f"  length range  : 2 <= l <= {aq.N - 4}")

    start_time = time.time()
    dumped_witnesses = []

    for index, faults in enumerate(fault_sets, start=1):
        adj = aq.adjacency_without_faults(faults)
        cycle_cache: Dict[int, Optional[Tuple[Vertex, ...]]] = {}

        witness_record = {
            "faults": [aq.format_edge(e) for e in sorted(faults)],
            "cases": [],
        }

        for e in aq.edges:
            if e in faults:
                continue

            u, v = e

            for length_l in range(2, aq.N - 3):
                result = find_path_and_cycle(
                    aq=aq,
                    adj=adj,
                    u=u,
                    v=v,
                    length_l=length_l,
                    cycle_cache=cycle_cache,
                )

                if result is None:
                    print("\nFAILED")
                    print(json.dumps(
                        {
                            "n": n,
                            "faults": [aq.format_edge(x) for x in sorted(faults)],
                            "edge": aq.format_edge(e),
                            "length_l": length_l,
                        },
                        indent=2,
                        ensure_ascii=False,
                    ))
                    return False

                if dump_path is not None:
                    path, cycle = result
                    witness_record["cases"].append({
                        "edge": aq.format_edge(e),
                        "length_l": length_l,
                        "path": aq.format_path(path),
                        "cycle": aq.format_path(cycle),
                    })

        if dump_path is not None:
            dumped_witnesses.append(witness_record)

        if index % 10 == 0 or index == len(fault_sets):
            elapsed = time.time() - start_time
            print(f"  processed {index}/{len(fault_sets)} fault sets "
                  f"({elapsed:.2f}s)")

    print(f"SUCCESS: AQ_{n} verified.")
    print(f"Elapsed time: {time.time() - start_time:.2f}s")

    if dump_path is not None:
        output = {
            "n": n,
            "statement": "one-fault edge-specified path-cycle cover theorem",
            "fault_sets_checked": len(fault_sets),
            "witnesses": dumped_witnesses,
        }
        with open(dump_path, "w", encoding="utf-8") as f:
            json.dump(output, f, indent=2, ensure_ascii=False)

        print(f"Witnesses written to: {dump_path}")

    return True


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Verify base cases n=3,4 for one-fault path-cycle covers in augmented cubes."
    )
    parser.add_argument(
        "--n",
        type=int,
        choices=[3, 4],
        help="Verify only AQ_3 or AQ_4. If omitted, both are verified.",
    )
    parser.add_argument(
        "--dump",
        type=str,
        default=None,
        help="Dump explicit witnesses to a JSON file. Use together with --n.",
    )

    args = parser.parse_args()

    if args.dump is not None and args.n is None:
        raise SystemExit("Error: --dump requires specifying --n 3 or --n 4.")

    if args.n is not None:
        ok = verify_n(args.n, dump_path=args.dump)
        raise SystemExit(0 if ok else 1)

    ok3 = verify_n(3)
    print()
    ok4 = verify_n(4)

    raise SystemExit(0 if (ok3 and ok4) else 1)


if __name__ == "__main__":
    main()